### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by grasses** [dyninc/DHCPTest-python#1]
Traceback (most recent call last):
  File "dhcp.2.py", line 175, in <module>
    ip_issued = issueRequest(dhcp_ip, dhcp_port, 4, disc_packet)
  File "dhcp.2.py", line 81, in issueRequest
    pcap_obj = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'

**Comment by ghost** [comment]
Does anyone understand what is going on here? Kevin Gray?

Kevin Short

On Thu, Nov 6, 2014 at 9:34 AM, xiaocao notifications@github.com wrote:

> Traceback (most recent call last):
> File "dhcp.2.py", line 175, in
> ip_issued = issueRequest(dhcp_ip, dhcp_port, 4, disc_packet)
> File "dhcp.2.py", line 81, in issueRequest
> pcap_obj = pcap.pcapObject()
> AttributeError: 'module' object has no attribute 'pcapObject'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dyninc/DHCPTest-python/issues/1.

## 

[image: Dyn logo, Dyn.com] http://dyn.com/
http://twitter.com/dyn http://twitter.com/dyninc   [image: Dyn facebook
account] http://facebook.com/dyn   [image: Dyn LinkedIn account]
http://linkedin.com/company/dyn

Kevin Short  / Principal Automation Engineer
 603 663 0471      603 785 7165      @kshortwindham
http://twitter.com/kshortwindham/

Follow us on LinkedIn for all things Internet Performance & our career
opportunities: http://linkd.in/SYAFHXhttp://linkedin.com/company/dyn

**Comment by ghost** [comment]
I don't know what that code is or does but if it wasn't a direct checkin break then it could be a library on the system changed? Those are my best guesses

~Kevin

**Comment by ghost** [comment]
Hi Kevin G,

It looks like it has been 3 years since you did that single commit. I do
not know if there is any action we ought to take.

Kevin S

On Thu, Nov 6, 2014 at 10:03 AM, Kevin Gray kgray@dyn.com wrote:

> I don't know what that code is or does but if it wasn't a direct checkin
> break then it could be a library on the system changed? Those are my best
> guesses
> 
> ~Kevin
> 
> On Nov 6, 2014, at 9:53 AM, Kevin Short kshort@dyn.com wrote:
> 
> Does anyone understand what is going on here? Kevin Gray?
> 
> Kevin Short
> 
> On Thu, Nov 6, 2014 at 9:34 AM, xiaocao notifications@github.com wrote:
> 
> > Traceback (most recent call last):
> > File "dhcp.2.py", line 175, in
> > ip_issued = issueRequest(dhcp_ip, dhcp_port, 4, disc_packet)
> > File "dhcp.2.py", line 81, in issueRequest
> > pcap_obj = pcap.pcapObject()
> > AttributeError: 'module' object has no attribute 'pcapObject'
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dyninc/DHCPTest-python/issues/1.
> 
> ## 
> 
> [image: Dyn logo, Dyn.com] http://dyn.com/
> http://twitter.com/dyn http://twitter.com/dyninc   [image: Dyn
> facebook account] http://facebook.com/dyn   [image: Dyn LinkedIn
> account] http://linkedin.com/company/dyn
> 
> Kevin Short  / Principal Automation Engineer
>  603 663 0471      603 785 7165      @kshortwindham
> http://twitter.com/kshortwindham/
> 
> Follow us on LinkedIn for all things Internet Performance & our career
> opportunities: http://linkd.in/SYAFHXhttp://linkedin.com/company/dyn

## 

[image: Dyn logo, Dyn.com] http://dyn.com/
http://twitter.com/dyn http://twitter.com/dyninc   [image: Dyn facebook
account] http://facebook.com/dyn   [image: Dyn LinkedIn account]
http://linkedin.com/company/dyn

Kevin Short  / Principal Automation Engineer
 603 663 0471      603 785 7165      @kshortwindham
http://twitter.com/kshortwindham/

Follow us on LinkedIn for all things Internet Performance & our career
opportunities: http://linkd.in/SYAFHXhttp://linkedin.com/company/dyn

**Comment by jstelmach** [comment]
If it is no longer functional, then we should remove it.

—
Joe Stelmach

**Comment by grasses** [comment]
.....update a new

**Comment by ghost** [comment]
Haha! I didn't even know it was my code, don't remember doing it, I wouldn't take any action on it

~Kevin

**Comment by feishengfei** [comment]
I also encounter this problem:

after 'pip install pypcap', you can import pcap, but same as @grasses :

frankzhou@XA014D:~/github/DHCPTest-python$ python ./dhcp_test.py  192.168.179.1 67 1
Traceback (most recent call last):
  File "./dhcp_test.py", line 175, in <module>
    ip_issued = issueRequest(dhcp_ip, dhcp_port, 4, disc_packet)
  File "./dhcp_test.py", line 81, in issueRequest
    pcap_obj = pcap.pcapObject()
AttributeError: 'module' object has no attribute 'pcapObject'
